version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - VITE_BINDUK_APP_URL=${VITE_BINDUK_APP_URL:-http://localhost}
        container_name: arsip-smk-mandiri-staging-app
        restart: always
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: global-postgres-db
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE:-arsip_smk_mandiri_stag}
            DB_USERNAME: ${DB_USERNAME:-postgres}
            DB_PASSWORD: ${DB_PASSWORD:-root}
            REDIS_HOST: redis
        volumes:
            - public_data_staging:/var/www/public_shared
            - storage_data_staging:/var/www/storage
        command: >
            sh -c "cp -a /var/www/public/. /var/www/public_shared/ && 
                   chown -R www-data:www-data /var/www/public_shared && 
                   chmod -R 755 /var/www/public_shared && 
                   php-fpm"
        networks:
            - global-vps-network

    queue-worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: arsip-smk-mandiri-staging-worker
        restart: always
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: global-postgres-db
            DB_PORT: 5432
            DB_DATABASE: ${DB_DATABASE:-arsip_smk_mandiri_stag}
            DB_USERNAME: ${DB_USERNAME:-postgres}
            DB_PASSWORD: ${DB_PASSWORD:-root}
            REDIS_HOST: redis
        volumes:
            - public_data_staging:/var/www/public_shared
            - storage_data_staging:/var/www/storage
        command: php artisan queue:work --verbose --tries=3
        networks:
            - global-vps-network
        depends_on:
            - app

    webserver:
        image: nginx:alpine
        container_name: arsip-smk-mandiri-staging-nginx
        restart: always
        ports:
            - '8081:80'
        volumes:
            - public_data_staging:/var/www/public
            - storage_data_staging:/var/www/storage
            - ./docker-config/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            - global-vps-network
        depends_on:
            - app

volumes:
    public_data_staging:
    storage_data_staging:
networks:
    global-vps-network:
        external: true
