name: Deploy Arsip SMK Mandiri Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🚀 Deploy to aaPanel VPS via SSH
      uses: appleboy/ssh-action@master
      env:
        ENV_STAG: ${{ secrets.ENV_PROD }}
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 2234
        envs: ENV_PROD
        script: |
          cd /www/wwwroot/arsip-smk-mandiri
          git pull origin staging
          
          echo "$ENV_PROD" > .env
          
          docker-compose --env-file .env up -d --build --force-recreate -V
          
          docker-compose exec -T app php artisan config:cache
          docker-compose exec -T app php artisan route:cache
          docker-compose exec -T app php artisan view:cache
          
          docker-compose exec -T app php artisan migrate --force